// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/8/27 13:34:52
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/suikati/Nanoconnect/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/plugins/**/*.{js,ts,mjs}","/home/suikati/Nanoconnect/composables/**/*.{js,ts,mjs}","/home/suikati/Nanoconnect/utils/**/*.{js,ts,mjs}","/home/suikati/Nanoconnect/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/suikati/Nanoconnect/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;