// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/8/25 10:29:18
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/feles/Desktop/Nanosuke-Linka/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/plugins/**/*.{js,ts,mjs}","C:/Users/feles/Desktop/Nanosuke-Linka/composables/**/*.{js,ts,mjs}","C:/Users/feles/Desktop/Nanosuke-Linka/utils/**/*.{js,ts,mjs}","C:/Users/feles/Desktop/Nanosuke-Linka/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/feles/Desktop/Nanosuke-Linka/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;